// Practice2/Practice2-frontend/src/pages/Signup/Signup.jsx
import { Form } from "react-router-dom";

export default function Signup() {
  return (
    <main className="flex min-h-full flex-col justify-center px-6 py-12 lg:px-8">
      <section className="sm:mx-auto sm:w-full sm:max-w-sm">
        <h1 className="mt-10 text-center text-3xl md:text-4xl font-bold leading-9 tracking-tight text-gray-900">
          Crear cuenta
        </h1>
      </section>

      <section className="mt-10 sm:mx-auto sm:w-full sm:max-w-sm">
        <Form action="/signup" method="POST" className="space-y-6">
          <div>
            <label
              className="block text-sm font-medium leading-6 text-gray-900 after:content-['*'] after:ml-1 after:text-red-500"
              htmlFor="email"
            >
              Correo
            </label>
            <div className="mt-2">
              <input
                autoComplete="email"
                className="block w-full rounded-md border-0 px-2.5 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
                id="email"
                name="email"
                placeholder="Tu correo"
                required
                type="email"
              />
            </div>
          </div>

          <div>
            <label
              className="block text-sm font-medium leading-6 text-gray-900 after:content-['*'] after:ml-1 after:text-red-500"
              htmlFor="username"
            >
              Usuario
            </label>
            <div className="mt-2">
              <input
                autoComplete="username"
                className="block w-full rounded-md border-0 px-2.5 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
                id="username"
                name="username"
                placeholder="Tu nombre de usuario"
                required
              />
            </div>
          </div>

          <div>
            <label
              className="block text-sm font-medium leading-6 text-gray-900 after:content-['*'] after:ml-1 after:text-red-500"
              htmlFor="lastname"
            >
              Apellido
            </label>
            <div className="mt-2">
              <input
                autoComplete="lastname"
                className="block w-full rounded-md border-0 px-2.5 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
                id="lastname"
                name="lastname"
                placeholder="Tu apellido"
                required
              />
            </div>
          </div>

          <div>
            <div className="flex items-center justify-between">
              <label
                className="block text-sm font-medium leading-6 text-gray-900 after:content-['*'] after:ml-1 after:text-red-500"
                htmlFor="password"
              >
                Contraseña
              </label>
            </div>
            <div className="mt-2">
              <input
                autoComplete="current-password"
                className="block w-full rounded-md border-0 px-2.5 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
                id="password"
                name="password"
                placeholder="Tu contraseña"
                required
                type="password"
              />
            </div>
          </div>
          <div>
            <button
              className="flex w-full justify-center rounded-md bg-indigo-600 px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
              type="submit"
            >
              Crear cuenta
            </button>
          </div>
        </Form>

        <p className="mt-10 text-center text-sm text-gray-500">
          ¿Ya tienes una cuenta?{" "}
          <a
            className="font-semibold leading-6 text-indigo-600 hover:text-indigo-500"
            href="/signin"
          >
            Inicia sesión
          </a>
        </p>
      </section>
    </main>
  );
}

// Practice2/angular-client/src/app/auth/signup/signup.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { AuthService } from '../../core/services/auth.service';
import { Router } from '@angular/router';

@Component({
  standalone: true,
  imports: [ReactiveFormsModule],
  templateUrl: './signup.component.html',
  styles: ``
})
export default class SignupComponent implements OnInit {
  signupForm!: FormGroup;

  constructor(private fb: FormBuilder, private auth: AuthService, private router: Router) { }

  ngOnInit(): void {
    this.signupForm = this.fb.group({
      username: ['', [Validators.required]],
      lastname: ['', [Validators.required]],
      email: ['', [Validators.required, Validators.email]],
      password: ['', [Validators.required, Validators.minLength(6)]]
    });
  }

  onSubmit(): void {
    if (this.signupForm.valid) {
      console.log(this.signupForm.value);
      const { username, lastname, email, password } = this.signupForm.value;
      this.signUp();
    }
  }

  public signUp(): void {
    const { username, lastname, email, password } = this.signupForm.value;
    this.auth.signUp(username, lastname, email, password).subscribe({
      next: () => {
        this.router.navigate(['/landing/home']);
      },
      error: (error) => {
        console.error("Signup failed", error);
      }
    });
  }

}

<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto flex flex-wrap items-center w-full">
    <div
      class="lg:w-2/6 md:w-3/5 bg-gray-100 rounded-lg p-8 flex flex-col md:mx-auto w-full mt-10 md:mt-0"
    >
      <h2 class="text-gray-900 text-lg font-medium title-font mb-5">Sign Up</h2>
      <form [formGroup]="signupForm" (ngSubmit)="onSubmit()">
        <div class="relative mb-4">
          <label for="username" class="leading-7 text-sm text-gray-600"
            >Username</label
          >
          <input
            formControlName="username"
            type="text"
            id="username"
            name="username"
            class="w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out"
          />
          @if (signupForm.get('username')?.invalid &&
          signupForm.get('username')?.touched) {
          <div class="text-red-500 text-sm">Username is required.</div>
          }
        </div>
        <div class="relative mb-4">
          <label for="lastname" class="leading-7 text-sm text-gray-600"
            >Last Name</label
          >
          <input
            formControlName="lastname"
            type="text"
            id="lastname"
            name="lastname"
            class="w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out"
          />
          @if (signupForm.get('lastname')?.invalid &&
          signupForm.get('lastname')?.touched) {
          <div class="text-red-500 text-sm">Last Name is required.</div>
          }
        </div>
        <div class="relative mb-4">
          <label for="email" class="leading-7 text-sm text-gray-600"
            >Email</label
          >
          <input
            formControlName="email"
            type="email"
            id="email"
            name="email"
            class="w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out"
          />
          @if (signupForm.get('email')?.invalid &&
          signupForm.get('email')?.touched) {
          <div class="text-red-500 text-sm">Valid email is required.</div>
          }
        </div>
        <div class="relative mb-4">
          <label for="password" class="leading-7 text-sm text-gray-600"
            >Password</label
          >
          <input
            formControlName="password"
            type="password"
            id="password"
            name="password"
            class="w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out"
          />
          @if (signupForm.get('password')?.invalid &&
          signupForm.get('password')?.touched) {
          <div class="text-red-500 text-sm">
            Password is required and must be at least 6 characters.
          </div>
          }
        </div>
        <button
          type="submit"
          [disabled]="signupForm.invalid"
          class="text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg"
        >
          Sign Up
        </button>
      </form>
      <p class="text-xs text-gray-500 mt-3">
        Literally you probably haven't heard of them jean shorts.
      </p>
      <p class="text-xs text-gray-500 mt-3">
        Already have an account?
        <a href="/signin" class="text-indigo-500 hover:underline">Sign In</a>.
      </p>
    </div>
  </div>
</section>
